
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=Oracle;DB_CLOSE_DELAY=-1
    username: sa
    password: 
    initialization-mode: always  # 自动初始化schema
  application:
    name: demo
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # 启用H2控制台（浏览器访问 /h2-console）
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true